# Generated by Django 4.0.2 on 2023-01-28 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_question_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
