# Generated by Django 4.0.2 on 2023-01-28 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_tags_alter_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
